name: Check PR Source

on:
  pull_request:
    branches:
      - producao

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar se a branch de origem é homologacao
        if: github.head_ref != 'homologacao'
        run: |
          echo "ERRO: Pull Requests para a branch 'produção' só são permitidos a partir da 'homologação'."
          exit 1
