name: Test SSH Banner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Read SSH Banner
        run: |
          timeout 10 bash -c 'exec 3<>/dev/tcp/177.44.248.36/22; cat <&3'
