name: Debug SSH

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: homologacao

    steps:
      - name: Criar chave
        run: |
          cat > key << 'EOF'
          ${{ secrets.SSH_KEY }}
          EOF
          chmod 600 key

      - name: Verificar chave
        run: |
          echo "PRIMEIRA LINHA:"
          head -n 1 key

          echo "ULTIMA LINHA:"
          tail -n 1 key

          echo "TIPO:"
          file key

          echo "TAMANHO:"
          wc -c key

      - name: Testar SSH
        run: |
          ssh -vvv \
            -i key \
            -o StrictHostKeyChecking=no \
            univates@177.44.248.36 \
            "whoami"
