name: Test SSH Raw

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH
        run: |
          ssh -vvv \
            -o StrictHostKeyChecking=no \
            -o PreferredAuthentications=none \
            univates@177.44.248.36
