name: Deploy
on:
  #workflow_dispatch
  push:
    branches:
      - homologacao
      - producao

jobs:
  deploy-homologacao:
    if: github.ref == 'refs/heads/homologacao'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Homologação
        run: |
          curl -X POST \
            -H "x-secret: ${{ secrets.DEPLOY_SECRET }}" \
            http://177.44.248.36:9000/hooks/deploy-hml

  deploy-producao:
    if: github.ref == 'refs/heads/producao'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Produção
        run: |
          curl -X POST \
            -H "x-secret: ${{ secrets.DEPLOY_SECRET }}" \
            http://177.44.248.36:9000/hooks/deploy-prod
