name: hHmologação Pipeline

on:
  push:
    branches:
      - homologação

  pull_request:
    branches:
      - homologação

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build projeto
        run: dotnet build --no-restore

      - name: Executar testes
        run: dotnet test --no-build