name: Hmologação Pipeline

on:
  push:
    branches:
      - homologacao

  pull_request:
    branches:
      - homologacao

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restaurar dependências
        run: dotnet restore src/RegistroReceitas

      - name: Build projeto
        run: dotnet build src/RegistroReceitas --no-restore

      - name: Executar testes
        run: dotnet test src/RegistroReceitas --no-build
