name: Test SSH

on:
  push:
    branches:
      - homologacao
      - producao

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Test
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Conectado!"
            whoami
            hostname
