name: Executar script homologação

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Executar script no servidor
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" \
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "bash /home/univates/gerencia_configuracao/comandos/levantar_homologacao.sh"
